imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    bundles:        [ FrontendBundle , TranslateBundle ]

    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

sp_bower:
    bin: /usr/local/bin/bower
    assetic:
        enabled: false
    bundles:
        FrontendBundle: ~
        TranslateBundle: ~

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        port:     %database_port%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        charset:  UTF8
#        # if using pdo_sqlite as your database driver, add the path in parameters.yml
#        # e.g. database_path: %kernel.root_dir%/data/data.db3
#        # path:     %database_path%
#
#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true

# Doctrine MongoDB Bundle Configuration
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_connection_string%
            options: %mongodb_connection_options%
    default_database: %mongodb_database%
    document_managers:
        default:
            auto_mapping: true
            mappings:
                FOSUserBundle: ~
#                AppBundle:
#                    type: annotation
#                    dir: %kernel.root_dir%/../src/AppBundle/Document
#                    prefix: AppBundle\Document

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: true
    routing_loader:
        default_format: json

# FOS User Bundle for ORM
#fos_user:
#    db_driver: orm
#    firewall_name: main
#    user_class: Flyers\BackendBundle\Entity\User

# FOS User Bundle for MongoDB
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: Flyers\BackendBundle\Document\User